In [1]:
import numpy as np

In [22]:
escalar1 = 5.898
vector1 = np.array([1,2,3])
matriz1= np.array([[1,2,12],[3,4,16]])
tensor1 = np.array([
[[125,125,125],[66,66,66],[76,123,200]],
[[12,76,99],[100,100,0],[0,88,88]]#,
#[[23,55,200],[200,0,200],[200,230,10]]
])

In [20]:
#vector1.shape
#matriz1.shape
tensor1.shape

(2, 3, 3)

In [11]:
escalar2 = 5.898
vector2 = [1,2,3]
matriz2= [[1,2],[3,4]]
tensor2 = [[[125,125,125],[66,66,66],[76,123,200]],
[[12,76,99],[100,100,0],[0,88,88]],
[[23,55,200],[200,0,200],[200,230,10]]]

In [21]:
tensor1.size

18

In [26]:
matriz1_t=matriz1.T
print(matriz1,"\n\n",matriz1_t)

[[ 1  2 12]
 [ 3  4 16]] 

 [[ 1  3]
 [ 2  4]
 [12 16]]
