In [1]:
import numpy as np

In [16]:
vector = np.array([1,2,3,4,5])
print("Este es nuestro vector:\n",vector)

Este es nuestro vector:
 [1 2 3 4 5]


In [17]:
matriz = np.array([[1,2,3,4,5],[12,34,76,10,50]])
print("Este es nuestra matriz:\n",matriz)

Este es nuestra matriz:
 [[ 1  2  3  4  5]
 [12 34 76 10 50]]


In [21]:
tensor = np.array([[[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]],
                    [[9,8,7,6,5],[90,80,70,60,50],[900,800,700,600,500]]])
print("Este es nuestro tensor:\n",tensor)

Este es nuestro tensor:
 [[[  1   2   3   4   5]
  [ 10  20  30  40  50]
  [100 200 300 400 500]]

 [[  9   8   7   6   5]
  [ 90  80  70  60  50]
  [900 800 700 600 500]]]


In [24]:
print(np.shape(tensor))
print(np.size(tensor))


(2, 3, 5)
30


In [25]:
tensor_T=tensor.T
print("Este es nuestro tensor transpuesto:\n",tensor_T)
print(np.shape(tensor_T))
print(np.size(tensor_T))

Este es nuestro tensor transpuesto:
 [[[  1   9]
  [ 10  90]
  [100 900]]

 [[  2   8]
  [ 20  80]
  [200 800]]

 [[  3   7]
  [ 30  70]
  [300 700]]

 [[  4   6]
  [ 40  60]
  [400 600]]

 [[  5   5]
  [ 50  50]
  [500 500]]]
(5, 3, 2)
30
